class ImageRes {
  ImageRes._();
  static const _imageBase = 'assets/images';
  static const logo = '$_imageBase/logo.png';
  static const chatvector = '$_imageBase/chat_vector.png';
  static const bg = '$_imageBase/background.png';
  static const icon = '$_imageBase/ICON.png';
  static const page0 = '$_imageBase/page0.png';
  static const page1 = '$_imageBase/page1.png';
  static const page2 = '$_imageBase/page2.png';
  static const page3 = '$_imageBase/page3.png';
  static const gg = '$_imageBase/gg.png';
  static const fb = '$_imageBase/fb.png';
  static const heartblue = '$_imageBase/heartblue.png';
  static const homeicon = '$_imageBase/home_alt_outline.png';
  static const filter = '$_imageBase/filter.png';
  static const tag1 = '$_imageBase/selectpreferences.png';
  static const tag2 = '$_imageBase/tag2.png';
  static const cir1 = '$_imageBase/hotdeal.png';
  static const cir2 = '$_imageBase/newson.png';
  static const cir3 = '$_imageBase/badget.png';
  static const cir4 = '$_imageBase/fvr.png';
  static const tick = '$_imageBase/ticks.png';
  static const bbi1 = '$_imageBase/ic1.png';
  static const bbi2 = '$_imageBase/ic2.png';
  static const bbi3 = '$_imageBase/ic3.png';
  static const bbi4 = '$_imageBase/ic4.png';
  static const line = '$_imageBase/line.png';
  static const bookicon = '$_imageBase/bookmarkicon.png';
  static const seticon = '$_imageBase/settingicon.png';
  static const payicon = '$_imageBase/paymenticon.png';
  static const notiicon = '$_imageBase/notifiicon.png';
  static const res = '$_imageBase/restaurant.png';
  static const menu = '$_imageBase/menu.png';
  static const order = '$_imageBase/order.png';
}
