

import 'dart:async';

      class SearchBloc{
        final searchcontroller = StreamController<List<String>>.broadcast();
        var data = [
          "banh mi",
          "goi cuon",
          "pho",
          "bun cha",
          "com tam",
          "bun thit nuong",
          "banh xeo",
          "mi quang",
          "xoi",
          "goi xoai",
          "bun bo hue",
          "bun rieu",
          "nem ran",
          "hu tieu",
          "cach lam",
          "oc",
          "cha ca",
          "goi ga",
          "banh canh",
          "lau",
          "thit kho",
          "banh trang tron",
          "thit bo",
          "ca kho to",
          "goi ngo sen",
          "ga nuong",
          "ca hap",
          "canh chua",
          "tom kho",
          "bun mam",
          "bo luc lac",
          "chao",
          "tom rim",
          "thit ga",
          "sup cua",
          "rau muong",
          "goi cuon tom thit",
          "dia oc",
          "pho bo",
          "che",
          "banh khot",
          "banh can",
          "mi xao",
          "thit kho tieu",
          "mi hoanh thanh",
          "banh flan",
          "cua rang me",
          "canh bun",
          "com rang",
          "thit nuong",
          "ghe",
          "tom xao",
          "thach dua",
          "bun mam soc trang",
          "bun dau mam tom",
          "rau cau",
          "goi kho bo",
          "suon nuong",
          "bun bo gio heo",
          "bun ca",
          "dua chua",
          "cha ca la vong",
          "khoai mon chien",
          "che ba mau",
          "che dau xanh",
          "thit ga ram me",
          "banh canh cua",
          "tra sua",
          "goi sua",
          "trai cay dam",
          "sup mang cua",
          "ga chien bot",
          "banh duc",
          "bun chao",
          "bun he",
          "che troi nuoc",
          "bap xao",
          "bap nuong",
          "xoi xeo",
          "thit ga chien nuoc mam",
          "mien luon",
          "bun xao",
          "dia ran",
          "dau hu",
          "ga hap muoi",
          "muc rim nuoc dua",
          "bun oc",
          "ca basa nuong",
          "goi dua leo",
          "com chien",
          "rau cau dua",
          "oc len xao dua",
          "banh gio",
          "banh day",
          "cu cai xao",
          "ga xao xa ot",
          "nem chua ran",
          "bun dau mam tom thit luoc",
          "goi cuon thit nuong",
          "cha tom",
          "rau muong xao toi",
          "dua xao",
          "ga chien sa ot",
          "muc xao chua ngot",
          "rau muong xao toi mo",
          "rau xao",
          "rau muong luoc",
          "bun dau mam tom thit rang",
          "muc xao me",
          "cang cua",
          "bun thang",
          "rau muong nau nam",
          "suon nuong chao",
          "goi ngo sen tom thit",
          "sup hai san",
          "com suon bi cha",
          "mien ga",
          "trau gac bep",
          "banh trang nuong",
          "cang cua chien bot",
          "cha gio",
          "com suon nuong",
          "goi mien tron",
          "chim cut chien",
          "bo bit tet",
          "che long nhan",
          "mien luon nhan thit",
          "banh canh cua trung cut",
          "chao long",
          "khoai mon xao dau hao",
          "cha ca thanh long",
          "goi dau hu",
          "nui xao thit bo",
          "com nieu",
          "com tam bi suon cha",
          "goi hai san",
          "rau muong xao toi mo hanh",
          "khoai tay chien",
          "goi sua tom thit",
          "bap cai xao thit bo",
          "mien ga nau ngon",
          "muc chien xu",
          "goi thit bo",
          "xoi man",
          "rau muong nau thit bam",
          "goi xoai thit bo",
          "rau muong nau thit ga",
          "mien xao tom",
          "goi ga bap cai",
          "com ga xoi mo",
          "goi sua thit ga",
          "che khuc bach",
          "mien luon tron",
          "che dau do",
          "banh gio chao quay",
          "com chay",
          "goi dau hu tom thit",
          "mien tron",
          "goi cuon rau muong",
          "rau cau dua non",
          "mi hoanh thanh xao tom",
          "goi dua leo tom thit",
          "rau muong xao toi thit",
          "goi vit",
          "bap xao thit ga",
          "goi sua dau phong",
          "nui xao tom thit",
          "rau muong xao",
          "mien ga tron",
          "rau muong xao toi bo",
          "nui xao",
          "banh gio nuong",
          "goi rau thom",
          "com xuong",
          "nui chien",
          "goi sua chua tom thit",
          "bap xao thit bo",
          "goi ngo sen dau do",
          "rau cau dua",
          "muc xao cay",
          "nui xao bo",
          "mien xao",
          "rau muong nau dau hao",
          "com hen",
          "nui xao mien",
          "com ga",
          "khoai mon xao thit bo",
          "mien ga nau thom",
          "bap xao tom",
          "goi xoai tom",
          "rau muong xao toi hanh",
          "com ga hai nam",
          "mien xao thit bo",
          "che dau trang",
          "goi dua chuot",
          "khoai tay chien trung",
          "che khoai mon",
          "mi quang ga",
          "banh mi trung",
          "che hoa cau",
          "tra xanh da",
          "thach rau cau",
          "com tron",
          "goi xoai tom thit",
          "chao trai",
          "rau muong xao trung",
          "canh cai dau hu",
          "com suon nuong mat ong",
          "bun mien ga",
          "goi ca song",
          "goi dua chuot thit ga",
          "rau muong luoc cham mam nem",
          "com nieu chay",
          "bun mien tom",
          "goi kho bo nuong mo hanh",
          "chao long chay",
          "com tam bi suon trung",
          "che bap",
          "chao vit",
          "banh beo",
          "muc chien",
          "banh mi kep thit",
          "banh canh cua ghe",
          "goi ngo sen",
          "rau muong nau tom",
          "bun mien tron",
          "bun mang vit",
          "rau muong xao toi thit ga",
          "che chuoi",
          "tra sua trai cay",
          "tra xanh",
          "rau muong nau thit bo",
          "canh khoai mon dau ha ca thac lac",
          "mi xao don",
          "rau muong nau gan heo",
          "khoai tay chien trung muoi",
          "che dau van",
          "goi rau muong",
          "banh mi chien tom",
          "che xoi nuoc",
          "muc xao dua cai",
          "chao oc",
          "com ga roti",
          "banh mi cha ca",
          "che chuoi nep nuong",
          "goi mien hai san",
          "cha que",
          "banh mi thit bo",
          "mi xao cua",
          "che troi nuoc",
          "goi ca bong lau",
          "goi lau",
          "banh hoi thit nuong",
          "mi quang tom thit",
          "banh mi trung muoi",
          "mi quang ga",
          "mi xao thit ga",
          "com chien duong chau",
          "che bap trai cay",
          "goi cuon cha lua",
          "banh bao",
          "com chien dua gang",
          "mi xao thit bo",
          "tra sua hoa qua",
          "tra sua tran chau",
          "rau muong xao toi mo",
          "chao vit bam",
          "chao ga",
          "tra sua trung",
          "canh bong thien ly",
          "chao tom",
          "mi xao hai san",
          "tra sua nuoc dua",
          "goi kho bo tron trai cay",
          "canh chua ca loc",
          "cha ca thac lac",
          "che khoai mon dua",
          "com chay chien",
          "bun cha ca",
          "tra sua trung ga",
          "rau muong luoc cham mam ruoc",
          "canh cua",
          "canh ga chien gion",
          "com rang dua bo",
          "mien ga nuoc dua",
          "bun ca thi la",
          "banh flan trai cay",
          "cha ca nuong",
          "che dau trang nep cam",
          "banh bot loc",
          "goi dua chuot tom thit",
          "rau cau dua trai cay",
          "banh khoai mi nuong",
          "com ga hoi an",
          "banh mi bo kho",
          "che trai cay",
          "canh khoai mon thit bam",
          "com hen tron",
          "bun bo nam bo",
          "banh xeo tom nhay",
          "com ga nuong mat ong",
          "che thai",
          "canh kho qua nhoi thit",
          "com rang dua chien gion",
          "canh sup lo",
          "bun mien thit ga",
          "banh uot cha lua",
          "com chien vit",
          "tra sua tran chau den",
          "rau cau cau",
          "banh cuon nhan thit",
          "canh chua ca",
          "com nieu trung",
          "goi cuon thit heo",
          "bun dau mam tom cua",
          "banh gio tom thit",
          "goi mien hai san",
          "che khoai lang",
          "canh kho qua dau ha ca thac lac",
          "tra sua tran chau trung",
          "bun cha",
          "canh dua",
          "tra sua tran chau trai cay",
          "che chuoi xao dau xanh",
          "goi tom thit",
          "bun dau mam tom oc",
          "banh gio chay",
          "canh rau day",
          "bun ca long xuyen",
          "banh hoi nem nuong",
          "che dau do trung muoi",
          "rau cau cam",
          "banh xeo muoi xiem",
          "goi xoai tom muc",
          "bun moc",
          "tra sua tran chau trung ga",
          "rau cau socola",
          "banh trang kep cha bong",
          "canh ga chien bo",
          "goi sua tom muc",
          "com ga ngu vi huong",
          "banh bot loc la",
          "canh mang nau thit",
          "banh hoi chao quay",
          "com chien thit bo",
          "goi ca trich",
          "bun mam soc trang",
          "banh gio nuong mo hanh",
          "com tam suon bi cha",
          "canh sup loai 2",
          "bun xao thap cam",
          "goi tom sua",
          "tra sua tran chau trung muoi",
          "bun xao hai san",
          "banh mi kep thit nuong",
          "goi dua chuot ca",
          "rau cau dua hanh nhan",
          "banh mi kep trung",
          "canh rau day nhoi thit",
          "banh xeo tom nhay",
          "canh khop",
          "che khoai mon dau xanh",
          "goi dua leo ca",
          "banh khoai mi chien",
          "canh sup cua",
          "banh trang tron tom thit",
          "goi kho bo nuong xa",
          "rau cau dua man",
          "bun xao bo",
          "canh thit bo",
          "che chuoi nep nuong",
          "goi sua cua",
          "banh mi kep cha ca",
          "canh suon non nau mong toi",
          "bun mien trung",
          "goi sua dua chuot",
          "com suon nuong chao",
          "canh cao luoc",
          "banh trang tron dau phong",
          "goi cuon chay",
          "com chay trung muoi",
          "canh rau lang nau thit",
          "banh trang tron trung",
          "goi dua leo tom ca",
          "che chuoi nep mo cha",
          "goi muc",
          "banh canh do bien",
          "com nieu trung ga",
          "canh sup lo",
          "goi cuon bi",
          "banh it tran",
          "che dau xanh trung muoi",
          "goi ngo sen bi",
          "com chien oc",
          "canh ca thac lac",
          "banh khoai mon chien trung",
          "goi dua leo tom",
          "banh my chao",
          "com ga phap",
          "canh ga nau ngo",
          "tra sua tran chau trung",
          "banh trang tron",
          "goi dua chuot cha bong",
          "che chuoi khoai",
          "goi mien trung",
          "banh trang tron muoi",
          "canh ca song",
          "banh uot tom chay",
          "che dau do tran chau",
          "goi mien tron rau thom",
          "banh trang tron trai cay",
          "canh cai dau xao thit",
          "bun mien cua",
          "che chuoi nep mo",
          "goi rau thom bi",
          "banh uot thit nuong",
          "canh cai dau nau thit",
          "goi su su tom muc",
          "banh trang tron dua",
          "che dau do trai cay",
          "goi vit cha bong",
          "banh uot thit cha bong",
          "canh cai thom thit",
          "bun thit nuong cha gio",
          "goi rau cuon thit luoc",
          "banh uot thit cha lua",
          "che dau trang duong phen",
          "goi thai lan",
          "banh uot thit nuong cha lua",
          "canh cai xao thit bam",
          "bun thit nuong heo quay",
          "goi sua cha bong",
          "banh uot tom",
          "che dau xanh bot bang",
          "goi thai",
          "banh uot tom nuong",
          "canh chua cai be xanh",
          "bun thit nuong trung op la",
          "goi sua dau xanh",
          "banh uot tom thit",
          "che dau trang nhan long nhan",
          "goi thai thit bo",
          "banh xeo",
          "canh chua ca diec",
          "bun thit nuong xuong",
          "goi thai thit nuong",
          "banh xeo dau xanh",
          "che dau xanh nhan long nhan",
          "goi tom",
          "banh xeo dau xanh thit nuong",
          "canh chua ca loc bong",
          "bun thit nuong xuong bo",
          "goi tom cha ca",
          "banh xeo mung bean",
          "che dau xanh suong sa hat luu",
          "goi tom chay",
          "banh xeo mung bean thit nuong",
          "canh chua ca loc mang",
          "bun thit nuong xa",
          "goi tom thit",
          "banh xeo suon",
          "che dau xanh trung ga",
          "goi vit chay",
          "banh xeo thit",
          "canh chua ca loc mien tay",
          "bun thit nuong xa ot",
          "goi xa lach thit bo",
          "banh xeo thit nuong",
          "che dau xanh tran chau",
          "goi xa lach trung",
          "banh xeo thit nuong chay",
          "canh chua ca linh",
          "bun thit nuong xoai",
          "goi xa lach trung luoc",
          "banh xeo tom",
          "che dau xanh tran chau trung muoi",
          "goi xa lach trung nuong",
          "banh xeo tom chay",
          "canh chua ca ro phi",
          "bun tom thit",
          "goi xa lach trung nuong thit ga",
          "banh xeo tom chien xu",
          "che dau xanh tran chau trung",
          "goi xa lach trung tron tom thit",
          "banh xeo tom chien",
          "canh chua ca trach",
          "bun xao",
          "goi xa lach trung tron tom thit bo",
          "banh xeo tom nuong",
          "che dau xanh tran chau trung ga",
          "goi xa lach trung tron tom thit ga",
          "banh xeo tom sua",
          "canh chua cai thia",
          "bun xao bo",
          "goi xa lach trung tron tom thit heo",
          "banh xeo tom thit",
          "che dau xanh tran chau trung ga",
          "goi xa lach trung tron tom thit suon",
          "banh xeo trung",
          "canh chua ca loc sua",
          "bun xao cua",
          "goi xa lach trung tron tom thit vit",
          "banh xeo trung bo",
          "che dau xanh tran chau trung muoi",
          "goi xa lach trung tron tom tom",
          "banh xeo trung ga",
          "canh chua ca thac lac",
          "bun xao ga",
          "goi xa lach trung tron tom",
          "banh xeo trung ga chay",
          "che dau xanh tran chau trung nuoc dua",
          "goi xa lach trung tron tom nuong",
          "banh xeo trung ga thit nuong",
          "canh chua ca thieu",
          "bun xao hai san",
          "goi xa lach trung tron tom sua",
          "banh xeo trung muoi",
          "che dau xanh xoi dau",
          "goi xa lach trung tron tom thit ga",
          "banh xeo trung muoi xiem",
          "canh chua ca tra",
          "bun xao muc",
          "goi xa lach trung tron tom thit heo",
          "banh xeo trung trai cay",
          "che dau xanh xoi xeo",
          "goi xa lach trung tron tom thit nuong",
          "banh xeo trung tran chau",
          "canh chua ca trung",
          "bun xao thit bo",
          "goi xa lach trung tron tom thit op la",
          "banh xeo trung xa lach",
          "che dau xanh xoi xoai",
          "goi xa lach trung tron tom tom",
          "banh xeo trung xa lach bo",
          "canh chua cua mang",
          "bun xao thit ga",
          "goi xa lach trung tron trai cay",
          "banh xeo trung xa lach nuong",
          "che dau xanh xoi xoai hat luu",
          "goi xa lach trung xa lach",
          "banh xeo trung xa lach tom",
          "canh chua cua nau dau ha ca thac lac",
          "bun xao thit heo",
          "goi xa lach trung xa lach thit ga",
          "banh xeo trung xiem",
          "che dau xanh xoi xoai tran chau",
          "goi xa lach trung xa lach thit heo",
          "banh xeo trung xiu mai",
          "canh chua cua trai",
          "bun xao thit nuong",
          "goi xa lach trung xa lach thit nuong",
          "banh xeo trung xuan hong",
          "che dau xanh xoi xoai trung muoi",
          "goi xa lach trung xa lach tom nuong",
          "banh xeo trung xuan hong thit nuong",
          "canh chua la giang",
          "bun xao thit xong khoi",
          "goi xa lach trung xa lach tom thit",
          "banh xeo trung xuan hong tom",
          "che dau xanh xoi xoai trung",
          "goi xa lach trung xa lach trai cay",
          "banh xeo trung xuan hong trung",
          "canh chua la vong",
          "bun xao tom",
          "goi xa lach trung xa lach trung",
          "banh xeo trung xuan hong trung nuong",
          "che dau xanh xoi xoai trung muoi",
          "goi xa lach trung xa lach trung muoi",
          "banh xeo trung xuan hong trung tom",
          "canh chua la vien",
          "bun xao tom thit",
          "goi xa lach trung xa lach trung tom",
          "banh xeo trung xuan hong trung tom nuong",];

        Search(String query){
          if(!query.isEmpty) Filter(query).then((value) => searchcontroller.sink.add(value));
          else searchcontroller.sink.add([]);
        }
        Future<List<String>>Filter(String query){
          var c=Completer<List<String>>();
          List<String>ans=[];
          data.forEach((element) {
            if(element.contains(query)) ans.add(element);
          });
          c.complete(ans);
          return c.future;
        }

        dispose(){
          searchcontroller.close();
        }
      }