// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ED5G3DrMh8lXaxvR4Gz_FtSrTZlnJCc',
    appId: '1:819148988617:web:d6e97efc735f4bfd0a6d18',
    messagingSenderId: '819148988617',
    projectId: 'testfirestore-b7869',
    authDomain: 'testfirestore-b7869.firebaseapp.com',
    storageBucket: 'testfirestore-b7869.appspot.com',
    measurementId: 'G-EDLYVDJC99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYURbP4HhjEnVG65nWAkqVJ5RNjQDs6_E',
    appId: '1:819148988617:android:41b98352aa4287980a6d18',
    messagingSenderId: '819148988617',
    projectId: 'testfirestore-b7869',
    storageBucket: 'testfirestore-b7869.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiLg0vGDlMxMfCng4q9P-XafId_mwq4uI',
    appId: '1:819148988617:ios:5085dec36136a6600a6d18',
    messagingSenderId: '819148988617',
    projectId: 'testfirestore-b7869',
    storageBucket: 'testfirestore-b7869.appspot.com',
    iosClientId: '819148988617-9s2gas4qk42dtobemelalja86h31t0sg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ishi.fooddeliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiLg0vGDlMxMfCng4q9P-XafId_mwq4uI',
    appId: '1:819148988617:ios:45ab712e0339c8560a6d18',
    messagingSenderId: '819148988617',
    projectId: 'testfirestore-b7869',
    storageBucket: 'testfirestore-b7869.appspot.com',
    iosClientId: '819148988617-6as4egmqh2mnsukrdoq4b4o86en708t6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ishi.fooddeliveryapp.RunnerTests',
  );
}
